{
    'name': 'Odoo Power BI Connector',
    'sequence': 10,
    'summary': 'Token-based API endpoint for Power BI integration',
    'category': 'Generic Modules',
    'version': '18.0.1.0',
    'license': 'Other proprietary',
    'author': "Infintor Solutions",
    "price": 50,
    "currency": 'USD',
    'website': "https://www.infintor.com",
    'depends': ['base'],
    'images': ['static/description/banner.gif'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/api_token_views.xml',
    ],
    'installable': True,
    'application': True,
}
